<!DOCTYPE html>
<html lang=en>
<head>
    <!-- so meta -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="HandheldFriendly" content="True">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
    <meta name="description" content="1. Xử lý exception trong methodE.g. Trong products_controller.rb ta có method sau: 12345def show  product = Product.find(12)  render layout_for_product_detailend  Nếu không có product nào có id = 12,">
<meta name="keywords" content="RUBY">
<meta property="og:type" content="article">
<meta property="og:title" content="Exception Trong Rails [Part 2]">
<meta property="og:url" content="https:&#x2F;&#x2F;hdchinh.github.io&#x2F;2020&#x2F;04&#x2F;23&#x2F;2020-04-23-handle-exception-in-rails&#x2F;index.html">
<meta property="og:site_name" content="Notes">
<meta property="og:description" content="1. Xử lý exception trong methodE.g. Trong products_controller.rb ta có method sau: 12345def show  product = Product.find(12)  render layout_for_product_detailend  Nếu không có product nào có id = 12,">
<meta property="og:locale" content="en">
<meta property="og:updated_time" content="2020-04-23T09:36:27.934Z">
<meta name="twitter:card" content="summary">
    
    
        
          
              <link rel="shortcut icon" href="/images/favicon.ico">
          
        
        
          
            <link rel="icon" type="image/png" href="/images/favicon-192x192.png" sizes="192x192">
          
        
        
          
            <link rel="apple-touch-icon" sizes="180x180" href="/images/apple-touch-icon.png">
          
        
    
    <!-- title -->
    <title>Exception Trong Rails [Part 2]</title>
    <!-- styles -->
    <link rel="stylesheet" href="/css/style.css">
    <!-- persian styles -->
    
      <link rel="stylesheet" href="/css/rtl.css">
    
    <!-- rss -->
    
    
</head>

<body class="max-width mx-auto px3 ltr">
    
      <div id="header-post">
  <a id="menu-icon" href="#"><i class="fas fa-bars fa-lg"></i></a>
  <a id="menu-icon-tablet" href="#"><i class="fas fa-bars fa-lg"></i></a>
  <a id="top-icon-tablet" href="#" onclick="$('html, body').animate({ scrollTop: 0 }, 'fast');" style="display:none;"><i class="fas fa-chevron-up fa-lg"></i></a>
  <span id="menu">
    <span id="nav">
      <ul>
        
          <li><a href="/">Home</a></li>
        
          <li><a href="/archives/">Writing</a></li>
        
          <li><a href="/projects/">Projects</a></li>
        
          <li><a href="/til/">TIL</a></li>
        
      </ul>
    </span>
    <br/>
    <span id="actions">
      <ul>
        
        <li><a class="icon" href="/2020/05/12/2020-05-12-safe-navigation-operator/"><i class="fas fa-chevron-left" aria-hidden="true" onmouseover="$('#i-prev').toggle();" onmouseout="$('#i-prev').toggle();"></i></a></li>
        
        
        <li><a class="icon" href="/2020/03/16/2020-03-16-new-project-notes-2/"><i class="fas fa-chevron-right" aria-hidden="true" onmouseover="$('#i-next').toggle();" onmouseout="$('#i-next').toggle();"></i></a></li>
        
        <li><a class="icon" href="#" onclick="$('html, body').animate({ scrollTop: 0 }, 'fast');"><i class="fas fa-chevron-up" aria-hidden="true" onmouseover="$('#i-top').toggle();" onmouseout="$('#i-top').toggle();"></i></a></li>
        <li><a class="icon" href="#"><i class="fas fa-share-alt" aria-hidden="true" onmouseover="$('#i-share').toggle();" onmouseout="$('#i-share').toggle();" onclick="$('#share').toggle();return false;"></i></a></li>
      </ul>
      <span id="i-prev" class="info" style="display:none;">Previous post</span>
      <span id="i-next" class="info" style="display:none;">Next post</span>
      <span id="i-top" class="info" style="display:none;">Back to top</span>
      <span id="i-share" class="info" style="display:none;">Share post</span>
    </span>
    <br/>
    <div id="share" style="display: none">
      <ul>
  <li><a class="icon" href="http://www.facebook.com/sharer.php?u=https://hdchinh.github.io/2020/04/23/2020-04-23-handle-exception-in-rails/" target="_blank" rel="noopener"><i class="fab fa-facebook " aria-hidden="true"></i></a></li>
  <li><a class="icon" href="https://twitter.com/share?url=https://hdchinh.github.io/2020/04/23/2020-04-23-handle-exception-in-rails/&text=Exception Trong Rails [Part 2]" target="_blank" rel="noopener"><i class="fab fa-twitter " aria-hidden="true"></i></a></li>
  <li><a class="icon" href="http://www.linkedin.com/shareArticle?url=https://hdchinh.github.io/2020/04/23/2020-04-23-handle-exception-in-rails/&title=Exception Trong Rails [Part 2]" target="_blank" rel="noopener"><i class="fab fa-linkedin " aria-hidden="true"></i></a></li>
  <li><a class="icon" href="https://pinterest.com/pin/create/bookmarklet/?url=https://hdchinh.github.io/2020/04/23/2020-04-23-handle-exception-in-rails/&is_video=false&description=Exception Trong Rails [Part 2]" target="_blank" rel="noopener"><i class="fab fa-pinterest " aria-hidden="true"></i></a></li>
  <li><a class="icon" href="mailto:?subject=Exception Trong Rails [Part 2]&body=Check out this article: https://hdchinh.github.io/2020/04/23/2020-04-23-handle-exception-in-rails/"><i class="fas fa-envelope " aria-hidden="true"></i></a></li>
  <li><a class="icon" href="https://getpocket.com/save?url=https://hdchinh.github.io/2020/04/23/2020-04-23-handle-exception-in-rails/&title=Exception Trong Rails [Part 2]" target="_blank" rel="noopener"><i class="fab fa-get-pocket " aria-hidden="true"></i></a></li>
  <li><a class="icon" href="http://reddit.com/submit?url=https://hdchinh.github.io/2020/04/23/2020-04-23-handle-exception-in-rails/&title=Exception Trong Rails [Part 2]" target="_blank" rel="noopener"><i class="fab fa-reddit " aria-hidden="true"></i></a></li>
  <li><a class="icon" href="http://www.stumbleupon.com/submit?url=https://hdchinh.github.io/2020/04/23/2020-04-23-handle-exception-in-rails/&title=Exception Trong Rails [Part 2]" target="_blank" rel="noopener"><i class="fab fa-stumbleupon " aria-hidden="true"></i></a></li>
  <li><a class="icon" href="http://digg.com/submit?url=https://hdchinh.github.io/2020/04/23/2020-04-23-handle-exception-in-rails/&title=Exception Trong Rails [Part 2]" target="_blank" rel="noopener"><i class="fab fa-digg " aria-hidden="true"></i></a></li>
  <li><a class="icon" href="http://www.tumblr.com/share/link?url=https://hdchinh.github.io/2020/04/23/2020-04-23-handle-exception-in-rails/&name=Exception Trong Rails [Part 2]&description=" target="_blank" rel="noopener"><i class="fab fa-tumblr " aria-hidden="true"></i></a></li>
</ul>

    </div>
    <div id="toc">
      <ol class="toc"><li class="toc-item toc-level-2"><a class="toc-link" href="#1-Xu-ly-exception-trong-method"><span class="toc-number">1.</span> <span class="toc-text">1. Xử lý exception trong method</span></a></li><li class="toc-item toc-level-2"><a class="toc-link" href="#2-Xu-ly-exception-voi-controller"><span class="toc-number">2.</span> <span class="toc-text">2. Xử lý exception với controller</span></a></li><li class="toc-item toc-level-2"><a class="toc-link" href="#3-Xu-ly-exception-voi-controller-cha"><span class="toc-number">3.</span> <span class="toc-text">3. Xử lý exception với controller cha</span></a></li><li class="toc-item toc-level-2"><a class="toc-link" href="#4-Tach-exception-ra-module-rieng"><span class="toc-number">4.</span> <span class="toc-text">4. Tách exception ra module riêng</span></a></li><li class="toc-item toc-level-2"><a class="toc-link" href="#5-Bat-exception-chi-tiet-hon"><span class="toc-number">5.</span> <span class="toc-text">5. Bắt exception chi tiết hơn</span></a></li><li class="toc-item toc-level-2"><a class="toc-link" href="#6-Tao-them-cac-lop-exception"><span class="toc-number">6.</span> <span class="toc-text">6. Tạo thêm các lớp exception</span></a></li><li class="toc-item toc-level-2"><a class="toc-link" href="#7-Xu-ly-exception-trong-method"><span class="toc-number">7.</span> <span class="toc-text">7. Xử lý exception trong method</span></a></li><li class="toc-item toc-level-2"><a class="toc-link" href="#8-Ghi-log"><span class="toc-number">8.</span> <span class="toc-text">8. Ghi log</span></a></li><li class="toc-item toc-level-2"><a class="toc-link" href="#9-Tham-khao"><span class="toc-number">9.</span> <span class="toc-text">9. Tham khảo</span></a></li></ol>
    </div>
  </span>
</div>

    
    <div class="content index py4">
        
        <article class="post" itemscope itemtype="http://schema.org/BlogPosting">
  <header>
    
    <h1 class="posttitle" itemprop="name headline">
        Exception Trong Rails [Part 2]
    </h1>



    <div class="meta">
      <span class="author" itemprop="author" itemscope itemtype="http://schema.org/Person">
        <span itemprop="name">Notes</span>
      </span>
      
    <div class="postdate">
      
        <time datetime="2020-04-22T17:00:00.000Z" itemprop="datePublished">2020-04-23</time>
        
      
    </div>


      

      
    <div class="article-tag">
        <i class="fas fa-tag"></i>
        <a class="tag-link" href="/tags/RUBY/" rel="tag">RUBY</a>
    </div>


    </div>
  </header>
  

  <div class="content" itemprop="articleBody">
    <h2 id="1-Xu-ly-exception-trong-method"><a href="#1-Xu-ly-exception-trong-method" class="headerlink" title="1. Xử lý exception trong method"></a>1. Xử lý exception trong method</h2><p>E.g. Trong products_controller.rb ta có method sau:</p>
<figure class="highlight ruby"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br></pre></td><td class="code"><pre><span class="line"><span class="function"><span class="keyword">def</span> <span class="title">show</span></span></span><br><span class="line">  product = Product.find(<span class="number">12</span>)</span><br><span class="line"></span><br><span class="line">  render layout_for_product_detail</span><br><span class="line"><span class="keyword">end</span></span><br></pre></td></tr></table></figure>

<p>Nếu không có product nào có id = 12, đoạn code trên sẽ gặp lỗi, và người dùng sẽ nhận được 1 màn hình error server.</p>
<p>Không muốn điều này xảy ra, ta update lại đoạn code như sau:</p>
<figure class="highlight ruby"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br></pre></td><td class="code"><pre><span class="line"><span class="function"><span class="keyword">def</span> <span class="title">show</span></span></span><br><span class="line">  <span class="keyword">begin</span></span><br><span class="line">    product = Product.find(<span class="number">12</span>)</span><br><span class="line"></span><br><span class="line">    render layout_for_product_detail</span><br><span class="line">  <span class="keyword">rescue</span> StandardError =&gt; e</span><br><span class="line">    <span class="comment"># Do something good for user</span></span><br><span class="line">  <span class="keyword">end</span></span><br><span class="line"><span class="keyword">end</span></span><br></pre></td></tr></table></figure>

<p>Vậy là ổn, như trong bài phần 1, catch exception với StandardError là đủ tốt để áp dụng và có lẽ đủ tốt để pass review code.</p>
<h2 id="2-Xu-ly-exception-voi-controller"><a href="#2-Xu-ly-exception-voi-controller" class="headerlink" title="2. Xử lý exception với controller"></a>2. Xử lý exception với controller</h2><p>Phần 1 đã ổn, nhưng không được tốt, lý do là vì nếu chúng ta có 100 methods, vậy chúng ta sẽ lắp lại đoạn catch exception kia 100 lần. Không DRY chút nào, viết 1 chục method lặp lại cùng 1 exception thì có lẽ không pass được review code =))</p>
<p>Update: products_controller.rb</p>
<figure class="highlight ruby"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br></pre></td><td class="code"><pre><span class="line"><span class="class"><span class="keyword">class</span> <span class="title">ProductsController</span> &lt; ApplicationController</span></span><br><span class="line">  rescue_from StandardError, <span class="symbol">with:</span> <span class="symbol">:private_method_you_use_to_handle_exception</span></span><br><span class="line"></span><br><span class="line">  <span class="function"><span class="keyword">def</span> <span class="title">show</span></span></span><br><span class="line">    product = Product.find(<span class="number">12</span>)</span><br><span class="line"></span><br><span class="line">    render layout_for_product_detail</span><br><span class="line">  <span class="keyword">end</span></span><br><span class="line"></span><br><span class="line">  <span class="comment"># 100 methods nữa ở đây...</span></span><br><span class="line"></span><br><span class="line">  private</span><br><span class="line"></span><br><span class="line">  <span class="function"><span class="keyword">def</span> <span class="title">private_method_you_use_to_handle_exception</span></span></span><br><span class="line">    <span class="comment"># Do something good</span></span><br><span class="line">  <span class="keyword">end</span></span><br><span class="line"><span class="keyword">end</span></span><br></pre></td></tr></table></figure>

<p>Như vậy đỡ phải viết lặp đi lặp lại 100 lần. Có vẻ tốt hơn rồi, tuy nhiên đã đủ tốt?</p>
<h2 id="3-Xu-ly-exception-voi-controller-cha"><a href="#3-Xu-ly-exception-voi-controller-cha" class="headerlink" title="3. Xử lý exception với controller cha"></a>3. Xử lý exception với controller cha</h2><p>Vậy nếu ta có 100 controller, và chỉ để bắt StandardError mà chúng ta phải viết rescue_from cho cả 100 controller đó?</p>
<p>Ta có thể xử lý trường hơp trên bằng cách dùng rescue_from trong controller cha, ở đây thì cha của products controller là application controller.</p>
<figure class="highlight ruby"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br></pre></td><td class="code"><pre><span class="line"><span class="class"><span class="keyword">class</span> <span class="title">ApplicationControler</span> &lt; ActionController::Base</span></span><br><span class="line">  rescue_from StandardError, <span class="symbol">with:</span> <span class="symbol">:private_method_you_use_to_handle_exception</span></span><br><span class="line"></span><br><span class="line">  private</span><br><span class="line"></span><br><span class="line">  <span class="function"><span class="keyword">def</span> <span class="title">private_method_you_use_to_handle_exception</span></span></span><br><span class="line">    <span class="comment"># Do something good</span></span><br><span class="line">  <span class="keyword">end</span></span><br><span class="line"><span class="keyword">end</span></span><br><span class="line"></span><br><span class="line"><span class="class"><span class="keyword">class</span> <span class="title">ProductsController</span> &lt; ApplicationController</span></span><br><span class="line">  <span class="function"><span class="keyword">def</span> <span class="title">show</span></span></span><br><span class="line">    product = Product.find(<span class="number">12</span>)</span><br><span class="line"></span><br><span class="line">    render layout_for_product_detail</span><br><span class="line">  <span class="keyword">end</span></span><br><span class="line"><span class="keyword">end</span></span><br></pre></td></tr></table></figure>

<h2 id="4-Tach-exception-ra-module-rieng"><a href="#4-Tach-exception-ra-module-rieng" class="headerlink" title="4. Tách exception ra module riêng"></a>4. Tách exception ra module riêng</h2><p>Giờ chúng ta chỉ có 1 exception cơ bản, nhưng không gì đảm bảo được rằng thế giới quan ngoài kia có thể kìm hãm nổi tài năng của bạn, rất có thể vài năm sau project làm chơi ngày nào của bạn thành startup triệu đô? =)) logic và bussiness lúc đó phức tạp thêm chục/trăm/ngàn lần.</p>
<p>Nên tách exception handle sang 1 module riêng là lựa chọn không tồi cho hiện tại và là lựa chọn không thể tránh khỏi trong tương lai (project của bạn mập lên).</p>
<p>Bạn muốn tách moudle này vào đâu? tôi không biết, tôi thì bỏ vào concerns folder của folder controller cho nhanh.</p>
<figure class="highlight ruby"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br></pre></td><td class="code"><pre><span class="line"><span class="comment"># controllers/concerns/handle_exception.rb</span></span><br><span class="line"><span class="class"><span class="keyword">module</span> <span class="title">HandleException</span></span></span><br><span class="line">  included <span class="keyword">do</span></span><br><span class="line">    rescue_from StandardError <span class="keyword">do</span> <span class="params">|e|</span></span><br><span class="line">      <span class="comment"># Do something good</span></span><br><span class="line">    <span class="keyword">end</span></span><br><span class="line"> <span class="keyword">end</span></span><br><span class="line"><span class="keyword">end</span></span><br><span class="line"></span><br><span class="line"><span class="class"><span class="keyword">class</span> <span class="title">ApplicationControler</span> &lt; ActionController::Base</span></span><br><span class="line">  <span class="keyword">include</span> HandleException</span><br><span class="line"><span class="keyword">end</span></span><br></pre></td></tr></table></figure>

<p>Vậy là chúng ta đã tách đoạn logic xử lý exception ra khỏi controller.</p>
<h2 id="5-Bat-exception-chi-tiet-hon"><a href="#5-Bat-exception-chi-tiet-hon" class="headerlink" title="5. Bắt exception chi tiết hơn"></a>5. Bắt exception chi tiết hơn</h2><p>Đến mục số 4, mọi thứ đã khá tốt, tuy vậy, có nhiều exception trong rails (và framework nào cũng vậy). Standard là 1 exception rất chung chung, vì vậy chỉ bắt Standard exception có lẽ giành cho trường hợp chúng ta… lười, hoặc dự án không nhiều logic, hoặc không đủ thời gian để implement, deadline dí quá chạy không kịp, nên chạy được là tốt rồi chứ chả còn thời gian mà nghĩ đến exception tốt hay chưa.</p>
<p>Trong trường hợp bạn…rảnh hoặc dự án yêu cầu, hoặc leader khó tính, chúng ta nên bắt các exception chi tiết hơn và chỉ nên cover Standard sau cùng.</p>
<figure class="highlight ruby"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br></pre></td><td class="code"><pre><span class="line"><span class="comment"># controllers/concerns/handle_exception.rb</span></span><br><span class="line"><span class="class"><span class="keyword">module</span> <span class="title">HandleException</span></span></span><br><span class="line">  included <span class="keyword">do</span></span><br><span class="line">    <span class="comment"># Exception 1</span></span><br><span class="line">    rescue_from StandardError <span class="keyword">do</span> <span class="params">|e|</span></span><br><span class="line">      <span class="comment"># Do something good</span></span><br><span class="line">    <span class="keyword">end</span></span><br><span class="line"></span><br><span class="line">    <span class="comment"># Exception 2</span></span><br><span class="line">    rescue_from ActiveRecord::RecordNotFound <span class="keyword">do</span> <span class="params">|e|</span></span><br><span class="line">      <span class="comment"># Do something good</span></span><br><span class="line">    <span class="keyword">end</span></span><br><span class="line"></span><br><span class="line">    <span class="comment"># ... N exception nữa, tuỳ nhu cầu của bạn.</span></span><br><span class="line"> <span class="keyword">end</span></span><br><span class="line"><span class="keyword">end</span></span><br><span class="line"></span><br><span class="line"><span class="class"><span class="keyword">class</span> <span class="title">ApplicationControler</span> &lt; ActionController::Base</span></span><br><span class="line">  <span class="keyword">include</span> HandleException</span><br><span class="line"><span class="keyword">end</span></span><br></pre></td></tr></table></figure>

<blockquote>
<p>Theo thứ tự included, exception khai báo sau sẽ được gọi trước, vậy exception 2 sẽ được gọi trước exception 1. Do đó nên khai báo cho Standard exception làm exception đầu tiên.</p>
</blockquote>
<h2 id="6-Tao-them-cac-lop-exception"><a href="#6-Tao-them-cac-lop-exception" class="headerlink" title="6. Tạo thêm các lớp exception"></a>6. Tạo thêm các lớp exception</h2><p>Giả sử với lượng exception mặc định trong rails không đủ cho project tầm cỡ 4.0 của bạn? bạn muốn catch những exception đặc biệt mà bạn chỉ bạn nghĩ ra?</p>
<p>Chúng ta có thể tạo thêm các class exception để đáp ứng nhu cầu trên:</p>
<figure class="highlight ruby"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br><span class="line">21</span><br><span class="line">22</span><br><span class="line">23</span><br><span class="line">24</span><br><span class="line">25</span><br><span class="line">26</span><br><span class="line">27</span><br><span class="line">28</span><br><span class="line">29</span><br><span class="line">30</span><br><span class="line">31</span><br><span class="line">32</span><br></pre></td><td class="code"><pre><span class="line"><span class="comment"># controllers/concerns/handle_exception.rb</span></span><br><span class="line"><span class="class"><span class="keyword">module</span> <span class="title">HandleException</span></span></span><br><span class="line">  <span class="comment"># Khái báo class exception bạn tạo,</span></span><br><span class="line">  <span class="comment"># chúng đều kế thừa từ class StandardError</span></span><br><span class="line">  <span class="class"><span class="keyword">class</span> <span class="title">WeakPassword</span> &lt; StandardError;</span> <span class="keyword">end</span></span><br><span class="line"></span><br><span class="line">  included <span class="keyword">do</span></span><br><span class="line">    <span class="comment"># Exception 1</span></span><br><span class="line">    rescue_from StandardError <span class="keyword">do</span> <span class="params">|e|</span></span><br><span class="line">      <span class="comment"># Do something good</span></span><br><span class="line">    <span class="keyword">end</span></span><br><span class="line"></span><br><span class="line">    <span class="comment"># Exception 2</span></span><br><span class="line">    rescue_from ActiveRecord::RecordNotFound <span class="keyword">do</span> <span class="params">|e|</span></span><br><span class="line">      <span class="comment"># Do something good</span></span><br><span class="line">    <span class="keyword">end</span></span><br><span class="line"></span><br><span class="line"></span><br><span class="line">    <span class="comment"># Exception 3</span></span><br><span class="line">    rescue_from HandleException::WeakPassword <span class="keyword">do</span> <span class="params">|e|</span></span><br><span class="line">      <span class="comment"># <span class="doctag">TODO:</span> notification password too weak</span></span><br><span class="line">      <span class="comment"># <span class="doctag">TODO:</span> init recommmend password</span></span><br><span class="line">      <span class="comment"># <span class="doctag">TODO:</span> display recommend password for UI</span></span><br><span class="line">    <span class="keyword">end</span></span><br><span class="line"></span><br><span class="line">    <span class="comment"># ... N exception nữa, tuỳ nhu cầu của bạn.</span></span><br><span class="line"> <span class="keyword">end</span></span><br><span class="line"><span class="keyword">end</span></span><br><span class="line"></span><br><span class="line"><span class="class"><span class="keyword">class</span> <span class="title">ApplicationControler</span> &lt; ActionController::Base</span></span><br><span class="line">  <span class="keyword">include</span> HandleException</span><br><span class="line"><span class="keyword">end</span></span><br></pre></td></tr></table></figure>

<p>Như vậy, khi bạn validate mật khẩu của user submit lên, nếu không thoả mãn điều kiện là một mật khẩu đủ mạnh, <strong>raise</strong> exception đã khai báo.</p>
<h2 id="7-Xu-ly-exception-trong-method"><a href="#7-Xu-ly-exception-trong-method" class="headerlink" title="7. Xử lý exception trong method"></a>7. Xử lý exception trong method</h2><p>Lại quay lại bước 1, nhưng không phải chúng ta xử lý mọi exception trong từng method. Mà khi chúng ta có 1 đoạn logic đặc biệt, không lặp lại, và có tính quan trọng thì chúng ta nên catch exception ngay tại chỗ đoạn logic đó diễn ra:</p>
<ol>
<li>dễ đọc code</li>
<li>vì là 1 trường hợp logic quan trọng nên cũng cần những xử lý exception có thể quan trọng theo, chứ không chỉ là bắn bug ra terminal hay ghi log.</li>
</ol>
<figure class="highlight ruby"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br></pre></td><td class="code"><pre><span class="line"><span class="class"><span class="keyword">class</span> <span class="title">ChargesController</span> &lt; ApplicationController</span></span><br><span class="line">  <span class="function"><span class="keyword">def</span> <span class="title">important_method</span></span></span><br><span class="line">    <span class="keyword">begin</span></span><br><span class="line">      payment_intent = Stripe::PaymentIntent.create(</span><br><span class="line">        <span class="symbol">:amount</span> =&gt; source.amount,</span><br><span class="line">        <span class="symbol">:currency</span> =&gt; source.currency,</span><br><span class="line">        <span class="symbol">:source</span> =&gt; source.id,</span><br><span class="line">        <span class="symbol">:payment_method_types</span> =&gt; [source.type],</span><br><span class="line">        <span class="symbol">:description</span> =&gt; <span class="string">"PaymentIntent for Source webhook"</span>,</span><br><span class="line">        <span class="symbol">:confirm</span> =&gt; <span class="literal">true</span>,</span><br><span class="line">        <span class="symbol">:capture_method</span> =&gt; ENV[<span class="string">'CAPTURE_METHOD'</span>] == <span class="string">"manual"</span> ? <span class="string">"manual"</span> : <span class="string">"automatic"</span>,</span><br><span class="line">      )</span><br><span class="line">    <span class="keyword">rescue</span> Stripe::StripeError =&gt; e</span><br><span class="line">      status <span class="number">400</span></span><br><span class="line">      <span class="keyword">return</span> log_info(<span class="string">"Webhook: Error creating PaymentIntent: <span class="subst">#&#123;e.message&#125;</span>"</span>)</span><br><span class="line">    <span class="keyword">end</span></span><br><span class="line">  <span class="keyword">end</span></span><br><span class="line"><span class="keyword">end</span></span><br></pre></td></tr></table></figure>

<blockquote>
<p>Đoạn code trên được copy từ <a href="https://github.com/stripe/example-mobile-backend/blob/master/web.rb" target="_blank" rel="noopener">stripe sample code</a></p>
</blockquote>
<p>Như ví dụ trên, khi bạn xử dụng thư viện, hoặc api của bên thứ 3, có những exception đặc trưng cho từng loại thư viện, làm theo docs của thư viện đó thôi, nên bắt các exception ngay tại nơi logic đang diễn ra. Sau có dục thư viện đó đi hay update thì cũng dễ xử lý hơn.</p>
<h2 id="8-Ghi-log"><a href="#8-Ghi-log" class="headerlink" title="8. Ghi log"></a>8. Ghi log</h2><p>Cuối cùng, khi sản phẩm của bạn lên production, bạn cần ghi log, để đọc, truy vết điều tra lỗi khi cần.</p>
<p>Tôi hiện viết log theo cách sau:</p>
<figure class="highlight ruby"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br><span class="line">21</span><br><span class="line">22</span><br><span class="line">23</span><br><span class="line">24</span><br><span class="line">25</span><br><span class="line">26</span><br><span class="line">27</span><br><span class="line">28</span><br><span class="line">29</span><br><span class="line">30</span><br><span class="line">31</span><br><span class="line">32</span><br><span class="line">33</span><br><span class="line">34</span><br><span class="line">35</span><br><span class="line">36</span><br><span class="line">37</span><br><span class="line">38</span><br><span class="line">39</span><br><span class="line">40</span><br><span class="line">41</span><br><span class="line">42</span><br><span class="line">43</span><br><span class="line">44</span><br><span class="line">45</span><br><span class="line">46</span><br><span class="line">47</span><br><span class="line">48</span><br></pre></td><td class="code"><pre><span class="line"><span class="comment"># controllers/concerns/handle_log.rb</span></span><br><span class="line"><span class="class"><span class="keyword">module</span> <span class="title">HandleLog</span></span></span><br><span class="line">  <span class="function"><span class="keyword">def</span> <span class="title">write_log</span><span class="params">(e)</span></span></span><br><span class="line">    issue = <span class="string">"START: ---------------------------\n"</span></span><br><span class="line">    issue &lt;&lt; <span class="string">"TIME: <span class="subst">#&#123;Time.now.utc&#125;</span> \n"</span></span><br><span class="line">    issue &lt;&lt; <span class="string">"PARAMS: <span class="subst">#&#123;params.to_json&#125;</span> \n"</span></span><br><span class="line">    issue &lt;&lt; <span class="string">"MESSAGE: <span class="subst">#&#123;e.message&#125;</span>\n"</span></span><br><span class="line">    issue &lt;&lt; <span class="string">"----------------------------- :END\n"</span></span><br><span class="line"></span><br><span class="line">    Rails.logger.info issue</span><br><span class="line">  <span class="keyword">end</span></span><br><span class="line"><span class="keyword">end</span></span><br><span class="line"></span><br><span class="line"><span class="comment"># controllers/concerns/handle_exception.rb</span></span><br><span class="line"><span class="class"><span class="keyword">module</span> <span class="title">HandleException</span></span></span><br><span class="line">  <span class="comment"># Khái báo class exception bạn tạo,</span></span><br><span class="line">  <span class="comment"># chúng đều kế thừa từ class StandardError</span></span><br><span class="line">  <span class="class"><span class="keyword">class</span> <span class="title">WeakPassword</span> &lt; StandardError;</span> <span class="keyword">end</span></span><br><span class="line"></span><br><span class="line">  included <span class="keyword">do</span></span><br><span class="line">    <span class="comment"># Exception 1</span></span><br><span class="line">    rescue_from StandardError <span class="keyword">do</span> <span class="params">|e|</span></span><br><span class="line">      <span class="comment"># Do something good</span></span><br><span class="line">      write_log(e)</span><br><span class="line">    <span class="keyword">end</span></span><br><span class="line"></span><br><span class="line">    <span class="comment"># Exception 2</span></span><br><span class="line">    rescue_from ActiveRecord::RecordNotFound <span class="keyword">do</span> <span class="params">|e|</span></span><br><span class="line">      <span class="comment"># Do something good</span></span><br><span class="line">      write_log(e)</span><br><span class="line">    <span class="keyword">end</span></span><br><span class="line"></span><br><span class="line"></span><br><span class="line">    <span class="comment"># Exception 3</span></span><br><span class="line">    rescue_from HandleException::WeakPassword <span class="keyword">do</span> <span class="params">|e|</span></span><br><span class="line">      <span class="comment"># <span class="doctag">TODO:</span> notification password too weak</span></span><br><span class="line">      <span class="comment"># <span class="doctag">TODO:</span> init recommmend password</span></span><br><span class="line">      <span class="comment"># <span class="doctag">TODO:</span> display recommend password for UI</span></span><br><span class="line">    <span class="keyword">end</span></span><br><span class="line"></span><br><span class="line">    <span class="comment"># ... N exception nữa, tuỳ nhu cầu của bạn.</span></span><br><span class="line"> <span class="keyword">end</span></span><br><span class="line"><span class="keyword">end</span></span><br><span class="line"></span><br><span class="line"><span class="class"><span class="keyword">class</span> <span class="title">ApplicationControler</span> &lt; ActionController::Base</span></span><br><span class="line">  <span class="keyword">include</span> HandleLog</span><br><span class="line">  <span class="keyword">include</span> HandleException</span><br><span class="line"><span class="keyword">end</span></span><br></pre></td></tr></table></figure>

<h2 id="9-Tham-khao"><a href="#9-Tham-khao" class="headerlink" title="9. Tham khảo"></a>9. Tham khảo</h2><p>[1] <a href="http://rubylearning.com/satishtalim/ruby_exceptions.html" target="_blank" rel="noopener">http://rubylearning.com/satishtalim/ruby_exceptions.html</a></p>

  </div>
</article>



        
          <div id="footer-post-container">
  <div id="footer-post">

    <div id="nav-footer" style="display: none">
      <ul>
         
          <li><a href="/">Home</a></li>
         
          <li><a href="/archives/">Writing</a></li>
         
          <li><a href="/projects/">Projects</a></li>
         
          <li><a href="/til/">TIL</a></li>
        
      </ul>
    </div>

    <div id="toc-footer" style="display: none">
      <ol class="toc"><li class="toc-item toc-level-2"><a class="toc-link" href="#1-Xu-ly-exception-trong-method"><span class="toc-number">1.</span> <span class="toc-text">1. Xử lý exception trong method</span></a></li><li class="toc-item toc-level-2"><a class="toc-link" href="#2-Xu-ly-exception-voi-controller"><span class="toc-number">2.</span> <span class="toc-text">2. Xử lý exception với controller</span></a></li><li class="toc-item toc-level-2"><a class="toc-link" href="#3-Xu-ly-exception-voi-controller-cha"><span class="toc-number">3.</span> <span class="toc-text">3. Xử lý exception với controller cha</span></a></li><li class="toc-item toc-level-2"><a class="toc-link" href="#4-Tach-exception-ra-module-rieng"><span class="toc-number">4.</span> <span class="toc-text">4. Tách exception ra module riêng</span></a></li><li class="toc-item toc-level-2"><a class="toc-link" href="#5-Bat-exception-chi-tiet-hon"><span class="toc-number">5.</span> <span class="toc-text">5. Bắt exception chi tiết hơn</span></a></li><li class="toc-item toc-level-2"><a class="toc-link" href="#6-Tao-them-cac-lop-exception"><span class="toc-number">6.</span> <span class="toc-text">6. Tạo thêm các lớp exception</span></a></li><li class="toc-item toc-level-2"><a class="toc-link" href="#7-Xu-ly-exception-trong-method"><span class="toc-number">7.</span> <span class="toc-text">7. Xử lý exception trong method</span></a></li><li class="toc-item toc-level-2"><a class="toc-link" href="#8-Ghi-log"><span class="toc-number">8.</span> <span class="toc-text">8. Ghi log</span></a></li><li class="toc-item toc-level-2"><a class="toc-link" href="#9-Tham-khao"><span class="toc-number">9.</span> <span class="toc-text">9. Tham khảo</span></a></li></ol>
    </div>

    <div id="share-footer" style="display: none">
      <ul>
  <li><a class="icon" href="http://www.facebook.com/sharer.php?u=https://hdchinh.github.io/2020/04/23/2020-04-23-handle-exception-in-rails/" target="_blank" rel="noopener"><i class="fab fa-facebook fa-lg" aria-hidden="true"></i></a></li>
  <li><a class="icon" href="https://twitter.com/share?url=https://hdchinh.github.io/2020/04/23/2020-04-23-handle-exception-in-rails/&text=Exception Trong Rails [Part 2]" target="_blank" rel="noopener"><i class="fab fa-twitter fa-lg" aria-hidden="true"></i></a></li>
  <li><a class="icon" href="http://www.linkedin.com/shareArticle?url=https://hdchinh.github.io/2020/04/23/2020-04-23-handle-exception-in-rails/&title=Exception Trong Rails [Part 2]" target="_blank" rel="noopener"><i class="fab fa-linkedin fa-lg" aria-hidden="true"></i></a></li>
  <li><a class="icon" href="https://pinterest.com/pin/create/bookmarklet/?url=https://hdchinh.github.io/2020/04/23/2020-04-23-handle-exception-in-rails/&is_video=false&description=Exception Trong Rails [Part 2]" target="_blank" rel="noopener"><i class="fab fa-pinterest fa-lg" aria-hidden="true"></i></a></li>
  <li><a class="icon" href="mailto:?subject=Exception Trong Rails [Part 2]&body=Check out this article: https://hdchinh.github.io/2020/04/23/2020-04-23-handle-exception-in-rails/"><i class="fas fa-envelope fa-lg" aria-hidden="true"></i></a></li>
  <li><a class="icon" href="https://getpocket.com/save?url=https://hdchinh.github.io/2020/04/23/2020-04-23-handle-exception-in-rails/&title=Exception Trong Rails [Part 2]" target="_blank" rel="noopener"><i class="fab fa-get-pocket fa-lg" aria-hidden="true"></i></a></li>
  <li><a class="icon" href="http://reddit.com/submit?url=https://hdchinh.github.io/2020/04/23/2020-04-23-handle-exception-in-rails/&title=Exception Trong Rails [Part 2]" target="_blank" rel="noopener"><i class="fab fa-reddit fa-lg" aria-hidden="true"></i></a></li>
  <li><a class="icon" href="http://www.stumbleupon.com/submit?url=https://hdchinh.github.io/2020/04/23/2020-04-23-handle-exception-in-rails/&title=Exception Trong Rails [Part 2]" target="_blank" rel="noopener"><i class="fab fa-stumbleupon fa-lg" aria-hidden="true"></i></a></li>
  <li><a class="icon" href="http://digg.com/submit?url=https://hdchinh.github.io/2020/04/23/2020-04-23-handle-exception-in-rails/&title=Exception Trong Rails [Part 2]" target="_blank" rel="noopener"><i class="fab fa-digg fa-lg" aria-hidden="true"></i></a></li>
  <li><a class="icon" href="http://www.tumblr.com/share/link?url=https://hdchinh.github.io/2020/04/23/2020-04-23-handle-exception-in-rails/&name=Exception Trong Rails [Part 2]&description=" target="_blank" rel="noopener"><i class="fab fa-tumblr fa-lg" aria-hidden="true"></i></a></li>
</ul>

    </div>

    <div id="actions-footer">
        <a id="menu" class="icon" href="#" onclick="$('#nav-footer').toggle();return false;"><i class="fas fa-bars fa-lg" aria-hidden="true"></i> Menu</a>
        <a id="toc" class="icon" href="#" onclick="$('#toc-footer').toggle();return false;"><i class="fas fa-list fa-lg" aria-hidden="true"></i> TOC</a>
        <a id="share" class="icon" href="#" onclick="$('#share-footer').toggle();return false;"><i class="fas fa-share-alt fa-lg" aria-hidden="true"></i> Share</a>
        <a id="top" style="display:none" class="icon" href="#" onclick="$('html, body').animate({ scrollTop: 0 }, 'fast');"><i class="fas fa-chevron-up fa-lg" aria-hidden="true"></i> Top</a>
    </div>

  </div>
</div>

        
        <footer id="footer">
  <div class="footer-left">
    Copyright &copy; 2020 Tam Thể
  </div>
  <div class="footer-right">
    <nav>
      <ul>
         
          <li><a href="/">Home</a></li>
         
          <li><a href="/archives/">Writing</a></li>
         
          <li><a href="/projects/">Projects</a></li>
         
          <li><a href="/til/">TIL</a></li>
        
      </ul>
    </nav>
  </div>
</footer>

    </div>
    <!-- styles -->
<link rel="stylesheet" href="/lib/font-awesome/css/all.min.css">
<link rel="stylesheet" href="/lib/justified-gallery/css/justifiedGallery.min.css">

    <!-- jquery -->
<script src="/lib/jquery/jquery.min.js"></script>
<script src="/lib/justified-gallery/js/jquery.justifiedGallery.min.js"></script>
<!-- clipboard -->

  <script src="/lib/clipboard/clipboard.min.js"></script>
  <script type="text/javascript">
  $(function() {
    // copy-btn HTML
    var btn = "<span class=\"btn-copy tooltipped tooltipped-sw\" aria-label=\"Copy to clipboard!\">";
    btn += '<i class="far fa-clone"></i>';
    btn += '</span>'; 
    // mount it!
    $(".highlight .code pre").before(btn);
    var clip = new ClipboardJS('.btn-copy', {
      target: function(trigger) {
        return trigger.nextElementSibling;
      }
    });
    clip.on('success', function(e) {
      e.trigger.setAttribute('aria-label', "Copied!");
      e.clearSelection();
    })
  })
  </script>

<script src="/js/main.js"></script>
<!-- search -->

<!-- Google Analytics -->

<!-- Baidu Analytics -->

<!-- Disqus Comments -->


</body>
</html>
